package ui.view;

import domain.Usuario;
import javax.swing.JOptionPane;
import ui.controller.UsuarioController;

/**
 *
 * @author carlo
 */
public class DlgUsuario extends javax.swing.JDialog {

    Usuario usuario = new Usuario();
    private UsuarioController user;

    /**
     * Creates new form DlgUsuario
     */
    public DlgUsuario(java.awt.Frame parent, boolean modal, UsuarioController user) {
        super(parent, modal);
        initComponents();
        setLocationRelativeTo(null);
        setResizable(modal);
        this.user = user;
    }

    public void crearUsuario() {
        String rut = txtRut.getText();
        String nombre = txtNombre.getText();
        String email = txtxEmail.getText();
        String pass = txtPass.getText();

        if (rut.isEmpty() || nombre.isEmpty() || email.isEmpty() || pass.isEmpty()) {
            JOptionPane.showMessageDialog(null, "Los Campos no pueden estar vacios", "WARNING", JOptionPane.WARNING_MESSAGE);
        } else {

            Usuario existente = user.buscarPorEmail(email);
            if(existente != null) {
                JOptionPane.showMessageDialog(this, "El correo ya está registrado", "ERROR", JOptionPane.ERROR_MESSAGE);
                return;
            }

          
            usuario.setNombre(nombre);
            usuario.setEmail(email);
            usuario.setPass(pass);
            usuario.setTipoUsuario("user");

            user.crearUsuario(nombre, email, pass, pass);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        txtRut = new javax.swing.JTextField();
        txtNombre = new javax.swing.JTextField();
        txtxEmail = new javax.swing.JTextField();
        txtPass = new javax.swing.JTextField();
        btnGuardar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(204, 204, 204));
        jPanel2.setForeground(new java.awt.Color(0, 0, 0));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        txtRut.setBackground(new java.awt.Color(255, 255, 255));
        txtRut.setForeground(new java.awt.Color(0, 0, 0));
        jPanel2.add(txtRut, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 60, 420, 50));

        txtNombre.setBackground(new java.awt.Color(255, 255, 255));
        txtNombre.setForeground(new java.awt.Color(0, 0, 0));
        jPanel2.add(txtNombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 150, 420, 50));

        txtxEmail.setBackground(new java.awt.Color(255, 255, 255));
        txtxEmail.setForeground(new java.awt.Color(0, 0, 0));
        jPanel2.add(txtxEmail, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 240, 420, 50));

        txtPass.setBackground(new java.awt.Color(255, 255, 255));
        txtPass.setForeground(new java.awt.Color(0, 0, 0));
        jPanel2.add(txtPass, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 320, 420, 50));

        btnGuardar.setText("guardar");
        jPanel2.add(btnGuardar, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 420, 420, 50));

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 50, 580, 530));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 660, 630));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(DlgUsuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(DlgUsuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(DlgUsuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(DlgUsuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnGuardar;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JTextField txtNombre;
    private javax.swing.JTextField txtPass;
    private javax.swing.JTextField txtRut;
    private javax.swing.JTextField txtxEmail;
    // End of variables declaration//GEN-END:variables
}
