/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package ui.view;

import com.google.protobuf.Internal;
import domain.Asistencia;
import domain.Usuario;
import java.sql.SQLException;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import ui.controller.UsuarioController;

/**
 *
 * @author carlo
 */
public class FrmGestorUsuarios extends javax.swing.JFrame {

    private UsuarioController user;
    Usuario usuario = new Usuario();

    DlgEditarUsuario edit = new DlgEditarUsuario(this, true, user);

    /**
     * Creates new form FrmGestorUsuarios
     *
     * @param user
     */
    public FrmGestorUsuarios(UsuarioController user) {
        this.user = user;

        initComponents();
        setLocationRelativeTo(null);
        setResizable(false);
        // Obtener usuarios y mostrar en tabla
        List<Usuario> lista = null;
        lista = user.obtenerTodos();
        mostrarEnTabla(lista);
        
        configurarBotones();
    }

    private void mostrarEnTabla(List<Usuario> listaUsuarios) {
        DefaultTableModel model = new DefaultTableModel() {
            @Override
            public boolean isCellEditable(int row, int column) {
                return false; // celdas no editables
            }
        };

        model.addColumn("ID"); // columna oculta
        model.addColumn("Nombre");
        model.addColumn("Email");
        model.addColumn("Pass");

        tblUsuarios.setModel(model);

        // Ocultar columna ID
        tblUsuarios.getColumnModel().getColumn(0).setMinWidth(0);
        tblUsuarios.getColumnModel().getColumn(0).setMaxWidth(0);
        tblUsuarios.getColumnModel().getColumn(0).setWidth(0);
        tblUsuarios.getColumnModel().getColumn(0).setPreferredWidth(0);

        // Llenar la tabla con los usuarios de la lista
        for (Usuario u : listaUsuarios) {
            model.addRow(new Object[]{u.getId(), u.getNombre(), u.getEmail(), u.getPass()});
        }
    }

    private void configurarBotones() {
        // Botón Editar
        btnEditar.addActionListener(e -> {
            int fila = tblUsuarios.getSelectedRow();
            if (fila >= 0) {
                int id = (int) tblUsuarios.getValueAt(fila, 0);
                String nombre = (String) tblUsuarios.getValueAt(fila, 1);
                String email = (String) tblUsuarios.getValueAt(fila, 2);
                String pass = (String) tblUsuarios.getValueAt(fila, 3);

                Usuario usuarioSeleccionado = new Usuario();
                usuarioSeleccionado.setId(id);
                usuarioSeleccionado.setNombre(nombre);
                usuarioSeleccionado.setEmail(email);
                usuarioSeleccionado.setPass(pass);

                DlgEditarUsuario dlg = new DlgEditarUsuario(this, true, user);
                dlg.setUsuario(usuarioSeleccionado);
                dlg.setVisible(true);
            } else {
                JOptionPane.showMessageDialog(this, "Seleccione un usuario para editar.");
            }
        });

        // Botón Eliminar
        btnEliminar.addActionListener(e -> {
            int fila = tblUsuarios.getSelectedRow();
            if (fila >= 0) {
                int id = (int) tblUsuarios.getValueAt(fila, 0);

                int confirm = JOptionPane.showConfirmDialog(
                        this,
                        "¿Está seguro que desea eliminar este usuario?",
                        "Confirmar eliminación",
                        JOptionPane.YES_NO_OPTION
                );

                if (confirm == JOptionPane.YES_OPTION) {
                    user.eliminarUsuario(id);
                    JOptionPane.showMessageDialog(this, "Usuario eliminado correctamente");
                    mostrarEnTabla(user.obtenerTodos());
                }
            } else {
                JOptionPane.showMessageDialog(this, "Seleccione un usuario para eliminar.");
            }
        });
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblUsuarios = new javax.swing.JTable();
        btnCrear = new javax.swing.JButton();
        btnEditar = new javax.swing.JButton();
        btnEliminar = new javax.swing.JButton();
        btnSalir = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setForeground(new java.awt.Color(0, 0, 0));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        tblUsuarios.setFont(new java.awt.Font("Cascadia Mono", 1, 14)); // NOI18N
        tblUsuarios.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "NOMBRE", "EMAIL", "PASSWORD", "TIPO DE USUARIO"
            }
        ));
        tblUsuarios.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblUsuariosMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblUsuarios);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 110, 1050, 460));

        btnCrear.setText("Crear");
        btnCrear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCrearActionPerformed(evt);
            }
        });
        jPanel1.add(btnCrear, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 50, 170, 50));

        btnEditar.setText("Editar");
        btnEditar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditarActionPerformed(evt);
            }
        });
        jPanel1.add(btnEditar, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 50, 170, 50));

        btnEliminar.setText("Eliminar");
        jPanel1.add(btnEliminar, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 50, 170, 50));

        btnSalir.setText("salir");
        btnSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalirActionPerformed(evt);
            }
        });
        jPanel1.add(btnSalir, new org.netbeans.lib.awtextra.AbsoluteConstraints(960, 40, 110, 50));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1120, 630));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnEditarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnEditarActionPerformed

    private void btnCrearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCrearActionPerformed
        // TODO add your handling code here:
        DlgCrearUsuario usu = new DlgCrearUsuario(this, true, user);
        usu.setVisible(true);
    }//GEN-LAST:event_btnCrearActionPerformed

    private void btnSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalirActionPerformed
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_btnSalirActionPerformed

    private void tblUsuariosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblUsuariosMouseClicked
        // TODO add your handling code here:


    }//GEN-LAST:event_tblUsuariosMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCrear;
    private javax.swing.JButton btnEditar;
    private javax.swing.JButton btnEliminar;
    private javax.swing.JButton btnSalir;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblUsuarios;
    // End of variables declaration//GEN-END:variables
}
