/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package ui.view;

import com.formdev.flatlaf.intellijthemes.materialthemeuilite.FlatMaterialLighterIJTheme;
import domain.Usuario;
import java.awt.Color;
import java.util.Arrays;
import javax.swing.JOptionPane;
import ui.controller.AsistenciaController;
import ui.controller.UsuarioController;

/**
 *
 * @author leandrofuentesvega
 */
public class FrmLogin extends javax.swing.JFrame {

    private UsuarioController controller;
    private AsistenciaController asistencia;

    /**
     * Creates new form FrmLogin
     */
    public FrmLogin(UsuarioController controller, AsistenciaController asistencia) {
        initComponents();
        setLocationRelativeTo(null);
        setResizable(false);
        this.controller = controller;
        this.asistencia = asistencia;
        disenioBotones();

    }

    public void disenioBotones() {
        btnAdministrador.putClientProperty("JButton.buttonType", "roundRect");
        btnAdministrador.setForeground(Color.WHITE);
        btnIngresar1.putClientProperty("JButton.buttonType", "roundRect");
        btnIngresar1.setForeground(Color.WHITE);

    }

    public void ingresarLogin() {
        String email = txtCorreo.getText();
        char[] pass = PassUsuario.getPassword();

        if (email.isEmpty() || pass.length == 0) {
            JOptionPane.showMessageDialog(null, "Debe ingresar contraseña y usuario", "Error", JOptionPane.ERROR_MESSAGE);
            return;
        }

        String contrasenia = new String(pass);
        Arrays.fill(pass, ' ');

        try {
            // Llamar al controller de usuarios

            // Intentar login
            Usuario usuario = controller.login(email, contrasenia);

            if (usuario != null) {
                // Usuario validado
                //JOptionPane.showMessageDialog(this, "Bienvenido " + usuario.getNombre());

                dlgAsistencia asistencia = new dlgAsistencia(this, true, usuario.getId(), this.asistencia);

                asistencia.setVisible(true);

            } else {
                JOptionPane.showMessageDialog(this, "Usuario o contraseña incorrectos", "Error", JOptionPane.ERROR_MESSAGE);
            }

        } catch (Exception e) {
            e.printStackTrace();
            JOptionPane.showMessageDialog(this, "Error al validar usuario", "Error", JOptionPane.ERROR_MESSAGE);
        }
    }

    private void abrirAsistencia(Usuario usuario) {
        dlgAsistencia dlg = new dlgAsistencia(this, true, usuario.getId(), asistencia);
        dlg.setVisible(true);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        txtCorreo = new javax.swing.JTextField();
        btnIngresar1 = new javax.swing.JButton();
        lblPersonal1 = new javax.swing.JLabel();
        PassUsuario = new javax.swing.JPasswordField();
        btnAdministrador = new javax.swing.JButton();
        lblAdm = new javax.swing.JLabel();
        lblTitulo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(233, 233, 233));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        txtCorreo.setBackground(new java.awt.Color(233, 233, 233));
        txtCorreo.setFont(new java.awt.Font("Helvetica Neue", 0, 14)); // NOI18N
        txtCorreo.setForeground(new java.awt.Color(153, 153, 153));
        txtCorreo.setText("Ingresa tu correo");
        txtCorreo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCorreoActionPerformed(evt);
            }
        });
        jPanel1.add(txtCorreo, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 110, 300, 30));

        btnIngresar1.setBackground(new java.awt.Color(37, 99, 235));
        btnIngresar1.setFont(new java.awt.Font("Roboto", 1, 16)); // NOI18N
        btnIngresar1.setForeground(new java.awt.Color(255, 255, 255));
        btnIngresar1.setText("Ingresar");
        btnIngresar1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnIngresar1ActionPerformed(evt);
            }
        });
        jPanel1.add(btnIngresar1, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 210, 150, 40));

        lblPersonal1.setBackground(new java.awt.Color(51, 51, 51));
        lblPersonal1.setFont(new java.awt.Font("Roboto", 1, 20)); // NOI18N
        lblPersonal1.setForeground(new java.awt.Color(102, 102, 102));
        lblPersonal1.setText("Inicio de sessión personal");
        jPanel1.add(lblPersonal1, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 60, -1, -1));

        PassUsuario.setBackground(new java.awt.Color(233, 233, 233));
        PassUsuario.setText("Ingresa tu pass");
        jPanel1.add(PassUsuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 160, 300, 30));

        jPanel2.add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 100, 360, 310));

        btnAdministrador.setBackground(new java.awt.Color(37, 99, 235));
        btnAdministrador.setFont(new java.awt.Font("Roboto", 1, 16)); // NOI18N
        btnAdministrador.setForeground(new java.awt.Color(255, 255, 255));
        btnAdministrador.setText("Administrador");
        btnAdministrador.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAdministradorActionPerformed(evt);
            }
        });
        jPanel2.add(btnAdministrador, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 470, 150, 40));

        lblAdm.setBackground(new java.awt.Color(51, 51, 51));
        lblAdm.setFont(new java.awt.Font("Roboto", 1, 20)); // NOI18N
        lblAdm.setForeground(new java.awt.Color(102, 102, 102));
        lblAdm.setText("Ingreso administradores");
        jPanel2.add(lblAdm, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 430, -1, -1));

        lblTitulo.setBackground(new java.awt.Color(51, 51, 51));
        lblTitulo.setFont(new java.awt.Font("Roboto", 1, 24)); // NOI18N
        lblTitulo.setForeground(new java.awt.Color(102, 102, 102));
        lblTitulo.setText("Sistema de control asistencia");
        jPanel2.add(lblTitulo, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 250, -1, -1));

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1010, 610));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnAdministradorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAdministradorActionPerformed
        // TODO add your handling code here:
        FrmReportes reportes = new FrmReportes(asistencia);
        
        reportes.setVisible(true);
    }//GEN-LAST:event_btnAdministradorActionPerformed

    private void txtCorreoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCorreoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCorreoActionPerformed

    private void btnIngresar1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnIngresar1ActionPerformed
        // TODO add your handling code here:
        ingresarLogin();
    }//GEN-LAST:event_btnIngresar1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
         FlatMaterialLighterIJTheme.setup();
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            JOptionPane.showMessageDialog(null, "Error al aplicar el LookAndFeel: " + ex.getMessage());
        }

        //</editor-fold>

        /* Create and display the form */
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPasswordField PassUsuario;
    private javax.swing.JButton btnAdministrador;
    private javax.swing.JButton btnIngresar1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JLabel lblAdm;
    private javax.swing.JLabel lblPersonal1;
    private javax.swing.JLabel lblTitulo;
    private javax.swing.JTextField txtCorreo;
    // End of variables declaration//GEN-END:variables
}
